### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [Anecarat/Proyecto_Final_Bioinf2017-II#1]
OK

Recuerda cómo citar repositorios de datos, te faltó el artículo.

**Comment by AzaleaGuerra** [comment]
Suena bien. ¿Harás desde el preprocesamiento de los datos? 
El repositorio no parece estar muy bien documentado, así que tú no olvides organizar los directorios y explicar paso a paso lo que hiciste.

**Comment by Anecarat** [comment]
Es justo lo que estoy viendo. Ahorita estoy desmembrando el script de mothur que usaron para saber qué hicieron. Pero decidí darle una oportunidad pues tienen datos y un fin similares a los que trabajaré, ya que son datos de secuenciación por MiSeq del 16S de bacterias de hojas e insectos. 

Lo que me complica un poco la existencia es que yo lo que tengo ya de scripts en R son para datos procesados en QIIME y estoy checando si me pueden servir los archivos del repositorio para procesarlos con lo que tengo ya en R o ver qué show.

**Comment by AliciaMstt** [comment]
Si no también puedes cambiar a otro artículo que tengas los datos como los necesitas para utilizar tus scritps de R. Menciónalo aquí y actualiza tus avances 1.

**Comment by Anecarat** [comment]
Seguí su consejo y cambié de artículo base. Ya hice las actualizaciones en el archivos de avances 1. 

Saludos.

**Comment by AliciaMstt** [comment]
Bien
