### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [Anecarat/Proyecto_Final_Bioinf2017-II#2]
Ok, suena bien el repositorio de Lady Wagner. Solo que en tus avances 2 no nos dijiste exactamente qué harás. Dado que estás cambiando de proyecto, por favor menciona cosas concretas como en el avance 1.

**Comment by Anecarat** [comment]
Listo. Ya actualicé los avances y lo que me pediste está al final, bajo complemento de avances 2. 

Saludos.
